### ISSUE TITLE
Fix references

### ISSUE THREAD

**Issue by kbenoit** [lse-my459/lse-my459.github.io#2]
The references were not translated properly from LaTeX to markdown (using pandoc). Please see the Dropbox for the original. Need updating in the document and to be appended to the end.

**Comment by chmue** [comment]
Do you want me to copy-paste the raw text from LaTeX output or set up [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) or [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) to do it automatically? The latter requires generating the page on our side (not GH's) either manually or via CI.

**Comment by kbenoit** [comment]
Thanks, but no need for anything automatic. This is only a once-off transition from the older LaTeX-based handout, which I suggest we discontinue.

**Comment by chmue** [comment]
Ok. I quickly checked it out earlier and to keep using bibtex databases and automatically generated citations/reference lists would be more work than makes sense.

I will revert the change I made in that direction and copy-paste the text from the Latex output tomorrow.

**Comment by chmue** [comment]
With cba5a32c4329c1942fd9b70238fc8d391a273820 this issue should be resolved. 

Could you have a quick look @kbenoit and @pablobarbera and then close the issue if it looks good?

**Comment by kbenoit** [comment]
Looks good to me.
